cardapio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cardapio, name='cardapio')
]

hamburgueria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cardapio.urls')),
]

cardapio/models.py
from django.db import models

class Ingredientes(models.Model):
    nome = models.CharField(max_length=50)
    tipo = models.CharField(max_length=30)

    def __str__(self) -> str:
        return self.nome

class Prato(models.Model):
    nome_prato = models.CharField(max_length=50)
    tipo = models.CharField(max_length=30)
    descricao = models.CharField(max_length=50, default='Descrição')
    foto = models.ImageField(upload_to='', default='images.jpeg')

    def __str__(self) -> str:
        return self.nome_prato

class Cardapio(models.Model):
    prato = models.ForeignKey(Prato, on_delete=models.DO_NOTHING)
    Ingrediente = models.ForeignKey(Ingredientes, on_delete=models.DO_NOTHING)

cardapio/views.py
from django.shortcuts import render
from .models import Cardapio, Prato, Ingredientes


def cardapio(request):
    prato_list = Prato.objects.all()
    return render(request, 'cardapio.html', {'prato': prato_list})

cardapio/templates/cardapio.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}

  <link rel="stylesheet" href="{% static 'general/css/base.css' %}">
  <link rel="stylesheet" href="{% static 'general/css/general.css' %}">
  <link rel="stylesheet" href="{% static 'cardapio/css/cardapio.css' %}">
  <style>
    .card {
      width: 100%;
    }
  </style>
{% endblock %}
{% block 'body' %}

<!-- <div class="p-3 mb-2 bg-dark text-white"> --> 
  <div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for pratos in prato %}
      <div id="c5" class="col">
        <div onclick="exibir_form('1')" class="card">
          <img src="{% static ''|add:pratos.foto.url %}" class="card-img-top" alt="...">
        <!--  <img src="{{ pratos.foto.url }}" class="card-img-top" alt="..."> -->
          <div class="card-body">
            <h5 class="card-title" value="{{ingrediente.id}}">{{ pratos.nome_prato }}</h5>
            <p>Ingredientes: 
              {% for cardapio in pratos.cardapio_set.all %}
              {{ cardapio.Ingrediente.nome }}{% if not forloop.last %}, {% endif %}
              {% endfor %}
            </p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <div id="cardapio_teste" onclick="exibir_form('3')">
      <h5 class="card-title">Você clicou no prato</h5>
      <select onchange="exibir_form('2')">
        {% for ingrediente in prato %}
        <option value="{{ingrediente.id}}">{{ingrediente}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
<!-- </div> -->
<script src="{% static 'cardapio/js/cardapio.js' %}"></script>  
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hangar 252 - Hamburgueria</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'general/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'general/css/general.css' %}">
    
    <style>
      body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
        padding: 0;
        background-color: #250303;
      }
      
      .container-fluid {
      display: flex;
      flex-grow: 1;
      height: 100%;
      background-color: #160A0C;
      }

      .navbar {
      flex-basis: 80px;
      flex-grow: 0;
      flex-shrink: 0;
      flex-direction: column;
      background-color: #e0a912;
      }

      .navbar-brand {
      padding: 1rem;
      text-align: center;
      background-color: #160A0C;
      }

      .navbar-nav {
      display: flex;
      flex-direction: column;
      flex-grow: 1;
      padding-top: 1rem;
      background-color: #160A0C;
      }

      .nav-link {
      padding: 0.5rem 1rem;
      text-align: center;
      background-color: #160A0C;
      }

      .content {
      flex-grow: 1;
      padding: 2rem;
      background-color: #160A0C;
      }

      .search-button {
      background-color: #e0a912;
      }

    </style>

    <script src="https://kit.fontawesome.com/2632c2155c.js" crossorigin="anonymous"></script>

  </head>
  <body> 

    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">  
        <font face="Verdana"><a class="navbar-brand" href="#">Hangar 252</a></font>
       
       <!-- <span class="fa-solid fa-plane"></span> -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link">HOME</a>
            </li>
            <li class="nav-item">
            <!-- =<a class="nav-link" href="/admin">Área Restrita</a> -->
            </li>
            <li class="nav-item">
              <a class="nav-link">SOBRE</a>
            </li>
            <li class="nav-item">
              <a class="nav-link">CONTATO</a>
            </li>
           </ul>
          <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Encontre seu prato" aria-label="Search">
         <button class="btn btn-outline-success search-button" type="submit">Busca</button>
        </form>
       </div>
     </div>
   </nav>

    <!-- Adicionar o banner no começo da página -->

    <div class="container-fluid">
      <div class="content">
        <div class="row">
          <div class="col-md-12 text-center">
            <img src="{% static 'media/banner-hangar25.png' %}" alt="Banner" width="75%">
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="content">
        {% block 'body'%}
        {% endblock %}
      </div>
    </div>

    <!-- Resto do código... -->